name: "Release-pre-checks"

on:
  push:
    branches: [ "main-pre-checks" ]
  pull_request:
    branches: [ "main-pre-checks" ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Testing for public javascript library vulnerabilities 
        uses: mattorb/is-website-vulnerable@github-action_v1
        with:
          scan-url: "https://mattorb.com"

      
