name: "Release-pre-checks"

on:
  push:
    branches: [ "main-pre-checks" ]


jobs:
  security-check:
     name: security check-npm
     runs-on: ubuntu-latest
     steps:
      - name: security check
        run: |
           rm -r package.json package-lock.json
           npm init
           npm install
           npm audit
      
