name: workflow_01
on:
  push:
    branches: [ workflow-test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
         echo "workflow trigger test"
      - name: failed step
        run: echo "test"
      - name: Archive job output
        uses: actions/upload-artifact@v2
        with:
          name: job-output
          path: /
