name: workflow_01
on:
  push:
    branches: [ workflow-test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check workflow status
        run: |
             echo "test run"
             php artisan migrate
