name: workflow_02
on:
  push:
    branches: [ workflow-test-2 ]

jobs:
  Results-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get workflow ID
        run: |
          echo "Find the workflow ID"
          echo $(curl https://api.github.com/repos/${{ secrets.REPO_NAME }}/actions/workflows) | jq . > id.txt
          grep -B 3 '${{ secrets.WORKFLOW_NAME }}' id.txt > id1.txt && grep '"id"' id1.txt > id2.txt
          sed -i 's/      "id": //g' id2.txt && sed 's/,//g' id2.txt > id3.txt
          echo "completing the workflow id process"
      - name: get pre-check results
        run: |
          WORKFLOW_ID=$(cat id3.txt)
          echo "Get the pre-checks' status"
          echo $WORKFLOW_ID
          curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ secrets.GITHUB_REPO }}/actions/workflows/$WORKFLOW_ID/runs | sed -n '1,20p' > runs.txt
          grep '"conclusion":' runs.txt > runs1.txt
          sed -i 's/      "conclusion": "//g' runs1.txt && sed -i 's/",//g' runs1.txt
          if grep "success" runs1.txt; then
            echo "Pre-checks have proven successful"
          else
            echo "not working"
          exit 1
          fi
