name: workflow_01
on:
  push:
    branches: [ "workflow-test" ]

  workflow_dispatch:
     inputs:
      workflow_02:
        description: 'Ù‹Workflow 2 which will be triggered'
        required: true
        default: 'workflow_02'

      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: ':Ganesh-manoharan'

      workflow2_repo_github:
        description: 'repo-name'
        required: true
        default: ':reactapp-heroku'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
         echo "workflow trigger test"
