name: workflow_02
on:
  push:
    branches: [ workflow-test-2 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Call other workflow
        uses: Ganesh-manoharan/reactapp-heroku/.github/workflows/workflow-1.yml
        with:
          event: push
      - name: Call child workflow
        run: |
           echo "Calling child workflow"
           ${{ steps.workflow_02.outputs.child_output }}
      - name: Test
        run: |
         echo "workflow trigger test"
